CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login_id VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    user_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20),
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT uk_users_login_id UNIQUE (login_id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE pets (
    pet_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    pet_name VARCHAR(50) NOT NULL,
    species VARCHAR(20) NOT NULL,
    breed VARCHAR(100),
    birth_date DATE,
    gender VARCHAR(20),
    weight NUMERIC(6, 2),
    neutered BOOLEAN,
    medical_history TEXT,
    profile_image_url VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pets_pkey PRIMARY KEY (pet_id),
    CONSTRAINT fk_pets_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT pets_species_check CHECK (species IN ('DOG', 'CAT')),
    CONSTRAINT pets_gender_check CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE'))
);

CREATE TABLE vital_records (
    vital_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pet_id BIGINT NOT NULL,
    temperature NUMERIC(4, 1) NOT NULL,
    heart_rate INTEGER NOT NULL,
    respiratory_rate INTEGER NOT NULL,
    measured_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT vital_records_pkey PRIMARY KEY (vital_record_id),
    CONSTRAINT fk_vital_records_pet FOREIGN KEY (pet_id) REFERENCES pets (pet_id),
    CONSTRAINT vital_records_source_type_check CHECK (source_type IN ('DATASET', 'MANUAL')),
    CONSTRAINT vital_records_status_check CHECK (status IN ('NORMAL', 'WATCH', 'CAUTION', 'DANGER'))
);

CREATE TABLE questionnaires (
    questionnaire_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pet_id BIGINT NOT NULL,
    temperature NUMERIC(4, 1) NOT NULL,
    heart_rate INTEGER NOT NULL,
    respiratory_rate INTEGER NOT NULL,
    skin_condition VARCHAR(20) NOT NULL,
    itching BOOLEAN NOT NULL,
    hair_loss BOOLEAN NOT NULL,
    vomiting BOOLEAN NOT NULL,
    diarrhea BOOLEAN NOT NULL,
    appetite_level VARCHAR(20) NOT NULL,
    water_intake_level VARCHAR(20) NOT NULL,
    activity_level VARCHAR(20) NOT NULL,
    symptom_duration_days INTEGER NOT NULL,
    additional_symptoms TEXT,
    submitted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT questionnaires_pkey PRIMARY KEY (questionnaire_id),
    CONSTRAINT fk_questionnaires_pet FOREIGN KEY (pet_id) REFERENCES pets (pet_id),
    CONSTRAINT questionnaires_skin_condition_check
        CHECK (skin_condition IN ('NORMAL', 'REDNESS', 'DRY', 'RASH', 'OTHER')),
    CONSTRAINT questionnaires_appetite_level_check
        CHECK (appetite_level IN ('NORMAL', 'DECREASED', 'INCREASED')),
    CONSTRAINT questionnaires_water_intake_level_check
        CHECK (water_intake_level IN ('NORMAL', 'DECREASED', 'INCREASED')),
    CONSTRAINT questionnaires_activity_level_check
        CHECK (activity_level IN ('NORMAL', 'LOW', 'HIGH'))
);

CREATE TABLE health_predictions (
    prediction_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    questionnaire_id BIGINT NOT NULL,
    abnormal_probability NUMERIC(5, 4) NOT NULL,
    risk_grade VARCHAR(20) NOT NULL,
    primary_risk_factor VARCHAR(100),
    risk_factors_json JSONB,
    ai_summary TEXT,
    model_version VARCHAR(50) NOT NULL,
    predicted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT health_predictions_pkey PRIMARY KEY (prediction_id),
    CONSTRAINT uk_health_predictions_questionnaire UNIQUE (questionnaire_id),
    CONSTRAINT fk_health_predictions_questionnaire
        FOREIGN KEY (questionnaire_id) REFERENCES questionnaires (questionnaire_id),
    CONSTRAINT health_predictions_risk_grade_check
        CHECK (risk_grade IN ('NORMAL', 'WATCH', 'CAUTION', 'DANGER'))
);

CREATE TABLE health_alerts (
    alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pet_id BIGINT NOT NULL,
    prediction_id BIGINT,
    alert_type VARCHAR(20) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT health_alerts_pkey PRIMARY KEY (alert_id),
    CONSTRAINT fk_health_alerts_pet FOREIGN KEY (pet_id) REFERENCES pets (pet_id),
    CONSTRAINT fk_health_alerts_prediction
        FOREIGN KEY (prediction_id) REFERENCES health_predictions (prediction_id),
    CONSTRAINT health_alerts_alert_type_check CHECK (alert_type IN ('VITAL', 'PREDICTION')),
    CONSTRAINT health_alerts_severity_check CHECK (severity IN ('WATCH', 'CAUTION', 'DANGER'))
);

CREATE TABLE weekly_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pet_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    average_temperature NUMERIC(4, 1),
    average_heart_rate NUMERIC(6, 2),
    warning_count INTEGER NOT NULL,
    danger_count INTEGER NOT NULL,
    questionnaire_count INTEGER NOT NULL,
    average_risk_probability NUMERIC(5, 4),
    one_line_summary VARCHAR(255),
    report_content TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT weekly_reports_pkey PRIMARY KEY (report_id),
    CONSTRAINT fk_weekly_reports_pet FOREIGN KEY (pet_id) REFERENCES pets (pet_id),
    CONSTRAINT uk_weekly_reports_pet_period UNIQUE (pet_id, start_date, end_date)
);

CREATE TABLE health_diary_entries (
    diary_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pet_id BIGINT NOT NULL,
    record_date DATE NOT NULL,
    guardian_status VARCHAR(20) NOT NULL,
    note VARCHAR(300) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT health_diary_entries_pkey PRIMARY KEY (diary_entry_id),
    CONSTRAINT fk_health_diary_entries_pet FOREIGN KEY (pet_id) REFERENCES pets (pet_id),
    CONSTRAINT uk_health_diary_entries_pet_date UNIQUE (pet_id, record_date),
    CONSTRAINT health_diary_entries_guardian_status_check
        CHECK (guardian_status IN ('GOOD', 'WATCH'))
);

CREATE INDEX idx_health_diary_entries_pet_date
    ON health_diary_entries (pet_id, record_date);
