CREATE TABLE pet_lost_qr_profiles (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pet_id BIGINT NOT NULL,
    public_token VARCHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pet_lost_qr_profiles_pkey PRIMARY KEY (profile_id),
    CONSTRAINT uk_pet_lost_qr_profiles_pet UNIQUE (pet_id),
    CONSTRAINT uk_pet_lost_qr_profiles_token UNIQUE (public_token),
    CONSTRAINT fk_pet_lost_qr_profiles_pet
        FOREIGN KEY (pet_id) REFERENCES pets (pet_id) ON DELETE CASCADE
);

